app/routes-config.js
Reverts peeranha/peeranha-web#160
=> Revert "Change route for filtered communities questions"

app/containers/HomePage/Footer.jsx, app/containers/Support/Contacts.jsx, app/media-links.js
https://peerania.atlassian.net/browse/PEER-599
=> feat: add telegram link

app/common-messages.js, app/components/AskQuestionBanner/index.js, app/components/AskQuestionBanner/messages.js, app/containers/App/imports.js, app/containers/App/index.js, app/containers/Faq/index.js, app/containers/Faq/messages.js, app/containers/LeftMenu/MainLinks.jsx, app/containers/Tutorial/Aside.jsx, app/containers/Tutorial/Content.jsx, app/containers/Tutorial/Header.jsx, app/containers/Tutorial/actions.js, app/containers/Tutorial/constants.js, app/containers/Tutorial/index.js, app/containers/Tutorial/messages.js, app/containers/Tutorial/reducer.js, app/containers/Tutorial/saga.js, app/containers/Tutorial/selectors.js, app/images/tutorial.svg, app/images/tutorialPageHeader.svg, app/routes-config.js, app/style-constants.js, app/translations/en.json, app/translations/ru.json, app/tutorial/en.md, app/tutorial/ru.md, app/utils/mdManagement.js
Tutorials Section is ready for testing
=> UI: Video Tutorials Section

app/communities-config.js, app/containers/App/index.js, app/containers/LeftMenu/MainLinks.jsx, app/containers/Tutorial/Content.jsx, app/containers/Tutorial/Question.jsx, app/tutorial/en.md, app/tutorial/ru.md, package-lock.json, package.json
1. Wider clickable area for sub-sections
2. Show/hide Tutorial section in Telos and Ontology SIngle Community mode pages
3. Pause the video when closing sub-section
4. Video player size adapts based on screen sizes
=> Peer 679 video tutorial section bugs fixed

app/containers/Header/EnergyDropdown.jsx, app/containers/Header/NotificationIcon.jsx, app/containers/Header/NotificationsDropdown/index.js, app/containers/Header/View.jsx, app/containers/Header/WalletButton.jsx, app/containers/Header/WalletDropdown.jsx, app/containers/Header/messages.js, app/containers/LeftMenu/MobileLinksInWallet.jsx, app/containers/Wallet/index.js, app/containers/Wallet/selectors.js, app/translations/en.json, app/translations/ru.json
Notification icon for WalletButton when user has weeks with not picked up rewards
=> Peer 676 ] Notification icon for WalletButton

app/communities-config.js, app/components/ExistingCommunities/Content.jsx, app/components/FormFields/messages.js, app/components/FormFields/validate.js, app/containers/CreateCommunity/Form.jsx, app/containers/CreateCommunity/constants.js, app/containers/CreateCommunity/index.js, app/containers/CreateCommunity/messages.js, app/images/globe-outline-16.svg, app/translations/en.json, app/translations/ru.json, app/utils/communityManagement.js
* official site rendering for communities
* official site field in CreateCommunity Form
=> Url for communities

app/components/ExistingCommunities/Content.jsx, app/components/FormFields/validate.js, app/translations/en.json, app/translations/ru.json
* decrease community url font-size
* Official site field is optional, tip updated
=> [peer-699] url for communities

app/containers/ViewQuestion/UserInfo.jsx
fix on question page for question, answer, question comment and answer comment
=> fix/[peer-722 date fix for question, answer, question comment and answer comment

app/components/SignUpWrapper/SignUpOptions.jsx, app/containers/Login/Footer.jsx, app/containers/SendTips/CurrencyField.jsx, app/containers/SendTips/SendTipsForm.jsx, app/wallet-config.js, package-lock.json, package.json
Added check for mobile devices for login, sign up and send tips pages to show different wallets for mobile devices and PCs
=> #589 mobile tips

app/containers/ViewQuestion/BestAnswerMarker.jsx, app/containers/ViewQuestion/QuestionTitle.jsx
=> [peer-808] Tip question/answer buttons should not be displayed for not logged users

app/components/ExistingCommunities/Content.jsx, app/containers/Questions/QuestionFilter.js, app/containers/Questions/index.js, app/containers/Questions/reducer.js, app/containers/Questions/saga.js
* promoted questions display fix
* updateStoredQuestionsWorker fix
* Communities page -> questions link fix
=> [peer-959] Promoted questions display fix

app/containers/EditQuestion/saga.js, app/containers/Header/WalletDropdown/WalletButton.jsx, app/containers/ViewQuestion/Question.jsx, app/containers/ViewQuestion/QuestionTitle.jsx, app/containers/ViewQuestion/saga.js, app/utils/accountManagement.js, app/utils/constants.js, app/utils/datetime.js, app/utils/eosio.js, app/utils/questionsManagement.js, app/utils/walletManagement.js
*  edit community of promoted question
* send transaction with multiple actions
* dateNowInSeconds function
=> [peer-962] Edit community of promoted question

app/utils/communityManagement.js
* singleCommunityDetails cookies update after switching blogger community type
=> [peer-1016] unstyled single community header lins fix

app/containers/ChangeEmail/saga.js, app/containers/ForgotPassword/saga.js
ChangeEmail & ForgotPassword fix
=> [peer-1011] Email localization bugs fixes

app/translations/en.json, app/translations/ru.json
On the Communities page changed the "Questions" to "Posts"
=> PEER20-257

app/containers/ChangeLocale/index.js
commented out language selection
=> PEER20-274 Hide Language switch 

app/containers/SignUp/messages.js, app/containers/ViewProfilePage/AuthorizationData.jsx, app/containers/ViewProfilePage/SettingsOfUser.jsx, app/translations/en.json, app/translations/ru.json
1. Removed Referral Program and Tip from User Profile Settings.
2. At the Authorization data deleted “Telos Active”.
=> PEER20-275: 1. Removed Referral Program and Tip from User Profile Settings. 2. At the Authorization data deleted “Telos Active”.

app/containers/Questions/Content/Body/UserInfo.js, app/containers/Questions/QuestionFilter.js, app/containers/Questions/index.js, app/containers/Questions/saga.js
Displaying questions in a single community
=> PEER20-211 UI: Single community mode

app/components/QuestionForm/QuestionTypeField.js
After selecting a Post type, it should remain highlighted in blue
=> [PEER20-270] FIX: highlighting of selected post type on New post page

app/containers/LeftMenu/MobileLinksInProfile.jsx, app/containers/LeftMenu/MobileLinksInWallet/index.js
fix error: After press main menu button error Problem occured...  occurs when page are resizin
=> PEER20-289 - fix error

app/components/TopCommunities/index.js, app/containers/ViewProfilePage/ProfileViewForm.jsx
1. Profile page crashes when try open profile page for a new user;
2. Remove subscribed communities section completely;
3. Change header from My communities to Communities; 
4. Remove Subscribe from the card with reputation;
5. Communities section should always be visible when open user profile page
=> PEER20-302 UI fix and bag fix

app/containers/EosioProvider/saga.js, app/containers/EthereumProvider/saga.js, app/containers/Header/View.jsx, app/containers/LeftMenu/index.js
at:
1.New post
2.Upvote/downvote post at Discussion , ExpertQA, Tutorial 
3.Comment for Post at Discussion , ExpertQA, Tutorial 
4.Comment for Answer at Discussion , ExpertQA, Tutorial 
5.Community- Subscribe
6.select Community and Subscribe it  on Discussions , ExpertQA, Tutorials  pages 
7.Login button in sidebar on small screens
=> PEER20-362 Change the old login pop-up to the new one on all pages

app/containers/Login/saga.js, app/utils/ethereum.js
fix non-displayed scrollbar after closing login popup
=> PEER20-363 Disable scrollbar when login pop-up is shown

app/containers/App/index.js, app/containers/LeftMenu/MainLinks.jsx, app/containers/LeftMenu/View.jsx
389 - Add Feed page to Single Comm Pages;
387 - When User opens Single community pages- 404 error page opens.
=> PEER20-389  +  PEER20-387

app/containers/ViewQuestion/SeeOriginal.tsx
PR for [BLOC-1292](https://peer.youtrack.cloud/issue/BLOC-1292/Incorrect-icons-for-See-original)
=> [BLOC-1292] Incorrect icons for 'See original'

app/containers/EthereumProvider/index.js, package.json
PR for [BLOC-1289](https://peer.youtrack.cloud/issue/BLOC-1289/Add-OKX-WALLET-in-Connect-Wallet-to-onboard)
=> [BLOC-1289] Add OKX WALLET in Connect Wallet to onboard

.env, .env.prod, .env.staging, .env.test, app/containers/App/index.js, app/containers/Header/Logo.jsx, app/containers/Header/View.jsx, app/routes-config.js
PR for [BLOC-1298](https://peer.youtrack.cloud/issue/BLOC-1298/New-Landing-page)
* remove page
* add redirect from home to feed
* update logo link with www.peeranha.io (as env variable) for not single community mode
=> [BLOC-1298] New Landing page
